hearth_ocr: main.cpp
	c++ --std=c++11 -o hearth_ocr main.cpp -I/usr/local/include/mongocxx/v_noabi -I/usr/local/include/libmongoc-1.0 \-I/usr/local/include/bsoncxx/v_noabi -I/usr/local/include/libbson-1.0 \-L/usr/local/lib -lmongocxx -lbsoncxx -llept -ltesseract -lopencv_core -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_imgproc

